In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('C:\\Users\\HP\\Desktop\\walmart\\datasets\\cdp.csv' )

label_encoders = {}

le_program = LabelEncoder()
df['Program_encoded'] = le_program.fit_transform(df['Program'])
label_encoders['Program'] = le_program

le_status = LabelEncoder()
df['Status_encoded'] = le_status.fit_transform(df['Status'])
label_encoders['Status'] = le_status


def score_to_numeric(score):
    if pd.isna(score):
        return np.nan
    score_mapping = {
        'A': 4, 'A-': 3.7, 'B': 3, 'B-': 2.7, 'C': 2, 'C-': 1.7, 'D': 1, 'D-': 0.7, 'F': 0
    }
    scores = [score_mapping.get(s, np.nan) for s in score.split() if s in score_mapping]
    return np.nanmean(scores) if scores else np.nan

df['Score_processed'] = df['Score'].apply(score_to_numeric)

df['Score_processed'].fillna(df['Score_processed'].median(), inplace=True)
df_cleaned = df.drop(columns=['Program', 'Status', 'Score'])

df_cleaned.to_csv('C:\\Users\\HP\\Desktop\\walmart\\datasets\\updatedcdp.csv', index=False)

In [7]:
df

,Year,Program,Status,Score,Program_encoded,Status_encoded,Score_processed
0,2023,Climate Change,Submitted,B,1,3,3.0
1,2023,Forests,Submitted,B- B- B- B-,3,3,2.7
2,2023,Water Security,No Response,F,5,2,0.0
3,2022,Climate Change,Submitted,B,1,3,3.0
4,2022,Forests,Submitted,Not Scored,2,3,3.0
5,2022,Water Security,No Response,F,5,2,0.0
6,2021,Climate Change,Submitted,A-,1,3,3.7
7,2021,Forests,Submitted,C C C C,3,3,2.0
8,2021,Water Security,Submitted,Not Scored,5,3,3.0
9,2020,Climate Change,Submitted,A,1,3,4.0
10,2020,Forests,Submitted,C C C C,3,3,2.0
11,2020,Water Security,Submitted,C,5,3,2.0
12,2019,Climate Change,Submitted,A,1,3,4.0
13,2019,Forests,Submitted,C C C C,3,3,2.0
14,2019,Water Security,Submitted,C,5,3,2.0
15,2018,Climate Change,Submitted,A-,1,3,3.7
16,2018,Forests,No Response,F F F F,3,2,0.0
17,2018,Water,Submitted,C,4,3,2.0
18,2017,Climate Change,Submitted,B,1,3,3.0
19,2017,Forests,No Response,F F F F,3,2,0.0
20,2017,Water,Submitted,D-,4,3,0.7
21,2016,Climate Change,Submitted,B,1,3,3.0
22,2016,Forests,Declined to participate,Not Available,3,0,3.0
23,2016,Water,Submitted,Not Available,4,3,3.0
24,2015,Climate Change,Submitted,B 96,1,3,3.0
25,2015,Forests,Declined to participate,Not Available,3,0,3.0
26,2015,Water,Submitted,Not Available,4,3,3.0
27,2014,Climate Change,Submitted,A 98,0,3,4.0
28,2014,Forests,Declined to participate,Not Available,3,0,3.0
29,2014,Water,Submitted,Not scored,4,3,3.0
30,2013,Climate Change,Submitted,A- 94,1,3,3.7
31,2013,Forests,Declined to participate,Not Available,3,0,3.0
32,2013,Water,Submitted,Not scored,4,3,3.0
33,2012,Climate Change,Submitted,B 86,1,3,3.0
34,2012,Forests,No Response,Not Available,3,2,3.0
35,2012,Water,Information Provided,Not applicable,4,1,3.0
36,2011,Climate Change,Submitted,B 85,1,3,3.0
37,2011,Water,Declined to participate,Not applicable,4,0,3.0
38,2010,Climate Change,Submitted,B 86,1,3,3.0
39,2010,Water,Information Provided,Not applicable,4,1,3.0

In [10]:
df_cleaned

    Year  Program_encoded  Status_encoded  Score_processed
0   2023                1               3              3.0
1   2023                3               3              2.7
2   2023                5               2              0.0
3   2022                1               3              3.0
4   2022                2               3              3.0
5   2022                5               2              0.0
6   2021                1               3              3.7
7   2021                3               3              2.0
8   2021                5               3              3.0
9   2020                1               3              4.0
10  2020                3               3              2.0
11  2020                5               3              2.0
12  2019                1               3              4.0
13  2019                3               3              2.0
14  2019                5               3              2.0
15  2018                1               3              3.7
16  2018                3               2              0.0
17  2018                4               3              2.0
18  2017                1               3              3.0
19  2017                3               2              0.0
20  2017                4               3              0.7
21  2016                1               3              3.0
22  2016                3               0              3.0
23  2016                4               3              3.0
24  2015                1               3              3.0
25  2015                3               0              3.0
26  2015                4               3              3.0
27  2014                0               3              4.0
28  2014                3               0              3.0
29  2014                4               3              3.0
30  2013                1               3              3.7
31  2013                3               0              3.0
32  2013                4               3              3.0
33  2012                1               3              3.0
34  2012                3               2              3.0
35  2012                4               1              3.0
36  2011                1               3              3.0
37  2011                4               0              3.0
38  2010                1               3              3.0
39  2010                4               1              3.0

In [11]:
df_cleaned['Year'] = df_cleaned['Year'].astype(int)

X = df_cleaned[['Year', 'Program_encoded', 'Status_encoded']]
y = df_cleaned['Score_processed']

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor(n_esti mators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

In [48]:
model.score(X_test,y_test)

0.8818665000000002

In [49]:
model.predict([[2025,1,1]])

array([2.533])

In [50]:
joblib.dump(model, 'walmart_score_predictor_model.pkl')

['walmart_score_predictor_model.pkl']